# Dark theme config
[window]
padding = { x = 10, y = 10 }
decorations = "Full"

[terminal.shell]
program = "/bin/bash"
args = ["-l"]

[font]
size = 15.0

[font.normal]
family = "MartianMono Nerd Font"
style = "Regular"

[font.bold]
family = "MartianMono Nerd Font"
style = "Bold"

[font.italic]
family = "MartianMono Nerd Font"
style = "Regular"

[colors]
# Default colors
[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

# Normal colors
[colors.normal]
black   = '#45475a'
red     = '#f38ba8'
green   = '#a6e3a1'
yellow  = '#f9e2af'
blue    = '#89b4fa'
magenta = '#f5c2e7'
cyan    = '#94e2d5'
white   = '#bac2de'

# Bright colors
[colors.bright]
black   = '#585b70'
red     = '#f38ba8'
green   = '#a6e3a1'
yellow  = '#f9e2af'
blue    = '#89b4fa'
magenta = '#f5c2e7'
cyan    = '#94e2d5'
white   = '#a6adc8'
